Revert "[Tango->FCM] Fix the Drive push messaging."
This reverts commit 8cae3d68f0556ee145341afe4c2b7118f59092c9.

Reason for revert: Breaks beta compilation
../../ios/web_view/internal/sync/web_view_profile_sync_service_factory.mm:98:11: error: member access into incomplete type 'invalidation::ProfileInvalidationProvider'
          ->GetIdentityProvider());

Original change's description:
> [Tango->FCM] Fix the Drive push messaging.
> 
> Drive relies on DeprecatedProfileInvalidationProviderFactory for its invalidations.
> ProfileSyncService only calls SetActiveAccountId on the IdentityProvider
> from the ProfileInvalidationProvider implementation it uses.
> 
> If FCMInvalidations is enabled, the IdentityProvider used by
> DeprecatedProfileInvalidationProviderFactory is never initialized
> with the active account ID so never starts.
> 
> ProfileSyncService should call SetActiveAccountId on both IdentityProvider
> instances as long as DeprecatedProfileInvalidationProviderFactory is used.
> 
> TBR=melandory@chromium.org, treib@chromium.org, jzw@chromium.org
> 
> Bug: 897570
> Cq-Include-Trybots: luci.chromium.try:ios-simulator-cronet;luci.chromium.try:ios-simulator-full-configs
> Change-Id: Ie3dd272e90f490199a62f83c3837f0f1a5256784
> Reviewed-on: https://chromium-review.googlesource.com/c/1296494
> Commit-Queue: Tatiana Gornak <melandory@chromium.org>
> Reviewed-by: Marc Treib <treib@chromium.org>
> Reviewed-by: John Wu <jzw@chromium.org>
> Reviewed-on: https://chromium-review.googlesource.com/c/1329680
> Reviewed-by: Tatiana Gornak <melandory@chromium.org>
> Cr-Commit-Position: refs/branch-heads/3578@{#632}
> Cr-Branched-From: 4226ddf99103e493d7afb23a4c7902ee496108b6-refs/heads/master@{#599034}

TBR=treib@chromium.org,melandory@chromium.org,jzw@chromium.org

Change-Id: I12be7e1df54b51e70b8a08f85430293d51e7cce9
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 897570
Cq-Include-Trybots: luci.chromium.try:ios-simulator-cronet;luci.chromium.try:ios-simulator-full-configs
Reviewed-on: https://chromium-review.googlesource.com/c/1332933
Reviewed-by: Olivier Robin <olivierrobin@chromium.org>
Cr-Commit-Position: refs/branch-heads/3578@{#653}
Cr-Branched-From: 4226ddf99103e493d7afb23a4c7902ee496108b6-refs/heads/master@{#599034}